### ISSUE TITLE
每次+1，到9往10进的时候报错

### ISSUE THREAD

**Issue by likeflower950** [zoeblow/numberAnimate#1]
代码存在问题，
当每次+1，在到9往10进阶的时候，数据错乱
39
49
41
42
没办法到40进行转换

**Comment by Liquid-Zhangliquan** [comment]
这个问题得到解决了么，我也遇到了

**Comment by zoeblow** [comment]
请更新至1.1版本，未做大修改，久等了

**Comment by linwenfeng122** [comment]
> 请更新至1.1版本，未做大修改，久等了

还有一个问题就是任意数添加  比如说是7-> 14-> 21
